# Generated by Django 5.2 on 2025-05-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='perfiles_usuarios', to='accounts.perfil'),
        ),
    ]
