# Generated by Django 5.2 on 2025-04-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('codigo_barras', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=10)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.CharField(max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupos_lineas', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='linea_articulo', to='core.lineaarticulo')),
            ],
        ),
    ]
