# Generated by Django 5.2 on 2025-05-06 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_canalcliente_cliente_listaprecio_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=255)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'vendedores',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraCliente',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_pedido', models.CharField(max_length=50, unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Completada'), (4, 'Cancelada')], default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.usuario')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdenCompraCliente',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_item', models.PositiveIntegerField(default=1)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_item_orden_compra', to='core.articulo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.usuario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden_compra', to='core.ordencompracliente')),
            ],
        ),
    ]
